### ISSUE TITLE
Problema com novo formato IRPF 2023

### ISSUE THREAD

**Issue by ktakanopy** [staticdev/irpf-investidor#403]
Stacktrac:

```
Nome do arquivo: InfoCEI.xls
/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Período de'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/irpf-investidor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/irpf_investidor/__main__.py", line 25, in main
    ref_year, institution = irpf_investidor.report_reader.validate_header(filename)
  File "/usr/local/lib/python3.10/dist-packages/irpf_investidor/report_reader.py", line 84, in validate_header
    periods = basic_df["Período de"].iloc[0].split(" a ")
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'Período de'
```
Para executar, eu usei o Dockerfile:
```
FROM ubuntu:latest

# Instala pacote de linguagem Português
RUN apt-get update && \
    apt-get install -y language-pack-pt-base && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Instala Python 3.10
RUN apt-get update && \
    apt-get install -y python3.10 python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


COPY . .

# Instala irpf-investidor via pip
RUN pip3 install irpf-investidor


RUN pip3 install openpyxl

# Executa comando ao iniciar o container
CMD ["irpf-investidor"]
 
```

**Comment by staticdev** [comment]
Opa.. to pra soltar uma nova documentação, mas basicamente vc pega a planilha nova e coloca no template da antiga. Não vai dar tempo de desenvolver o novo modelo pra esse ano.

**Comment by ktakanopy** [comment]
Você pode mandar o header da antiga mano? Pois eu nào tenho algum formato.

**Comment by joaobispo2077** [comment]
Seria muito útil o header da antiga, se tiver aí @staticdev manda pra gente

**Comment by staticdev** [comment]
@ktakanopy @joaobispo2077 adicionei o template no projeto e nas instruções. To fechando aqui, ano que vem acho que rola a versão nova, infelizmente esse ano outros projetos tiveram prioridade.
