### ISSUE TITLE
Erro na hora de rodar (Compatibilidade novo Portal)

### ISSUE THREAD

**Issue by rodrigogomesantos** [staticdev/irpf-investidor#89]
**Olá Amigo! Eu usei esse programa o ano passado pra gerar meus relatórios e não tive problemas, mas esse ano acho que pq mudou o portal do CEI, não esta funcionando! Como eu não tinha um exel da versão antiga pra comparar não sei se é isso. Alguma dica?**

`PS D:\Usuario\Downloads\irpf-investidor-main\irpf-investidor-main> irpf-investidor
Nome do arquivo: InfoCEI.xls
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Período de'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\Scripts\irpf-investidor.exe\__main__.py", line 7, in <module>
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\irpf_investidor\__main__.py", line 27, in main
    ref_year, institution = irpf_investidor.report_reader.validate_header(filename)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\irpf_investidor\report_reader.py", line 79, in validate_header       
    periods = basic_df["Período de"].iloc[0].split(" a ")
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'Período de'
PS D:\Usuario\Downloads\irpf-investidor-main\irpf-investidor-main> `

**Comment by staticdev** [comment]
Putz, gerei o meu em 31/12 do ano passado e está funcionando. Preciso de mais dados pra saber o que está acontecendo:
- Sabe o dia que você gerou seu extrado de negociações?
- Qual o nome do arquivo que foi gerado? 
- Poderia me dizer se o caminho que você fez para gerar o arquivo é o mesmo que explica na página inicial das instruções?
- Quando você abre a planilha tem um cabeçalho similar a esse?
![image](https://user-images.githubusercontent.com/1446633/157305060-716ed88a-4fe8-4516-841a-6c8d66cc7b8a.png)

Desculpe o tanto de perguntas mas as respostas ajudam a ver o que tenho que mexer.

**Comment by felipejfc** [comment]
acho que o problema dele eh estar usando um xls gerado pelo novo portal do investidor, que nao eh compativel com seus scripts

outro problema que encontrei aqui eh que quando tento usar pra o ano de 2021, nao tem suporte, os emulumentos nao estao la e mesmo no codigo tem uma checagem de ano <2021, vc chegou a atualizar pro exercicio do ano passado msm?

**Comment by rodrigogomesantos** [comment]
Erro meu de não ter esclarecido melhor! Eu achei que estava atualizado, pro novo portal, mas descobri que por mais que a data de acesso pro antigo estivesse expirada, dava pra acessar ainda! Ai rodei com a planilha antiga e deu boa! só precisei desabilitar a função de verificação do ano. mas acho que não é a melhor estratégia correto? 

- Outra duvidada/sugestão, se atualizar para pegar dados da nova planilha do novo portal, seria perfeito!  Hoje eu uso a Rico, e agora a XP comprou eles, com isso o CNPJ da corretora acabou mudando, então eu tenho que gerar duas planilhas de duas corretoras usando o extrato do CEI antigo. Já com o novo extrato, ele contorna esse problema colocando tudo direto na linha qual corretora cada papel foi comprado. 
nova planilha:
![image](https://user-images.githubusercontent.com/50123155/157444147-172124b1-432e-4727-a534-bcc250954da4.png)

- Ele não reconhece o mercado fracionado 
![image](https://user-images.githubusercontent.com/50123155/157443787-d0c30f12-5c80-412f-8450-906ab65f9f29.png)
precisei remover o F das ações pra rodar

**Comment by staticdev** [comment]
Vou lancar uma versao nova com essas correcoes. Caso nao tenha retorno sobre a taxa de emolumentos vou colocar a taxa atual, varia praticamente nada.

**Comment by staticdev** [comment]
@rodrigogomesantos e @felipejfc corrigi os problemas apontados aqui referente ao ano de 2021 e ações fracionárias. É para funcionar agora na versão 2022.2.

Quanto ao novo formato XLSX [criei um issue](https://github.com/staticdev/irpf-investidor/issues/95) de melhoria para adicionar no futuro. Estou fechando aqui. Coloquei no README que temos que rodar com o formato antigo por enquanto.

Obrigado.
